Cleaning
isfegu/anonymath pull request #4
Opened 2022-02-05 08:14 UTC by qbreis

2022-02-05 09:16 UTC, isfegu requested changes
Respecto a conventional commits, has usado "perf", que se usa para mejoras en el rendimiento. Los commits que has hecho encajan mejor como "feat", ya que son nuevas funcionalidades o mejoras funcionales. Este enlace explica cada una de las opciones: https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines
Y recuerda que los mensajes de commit deben estar en imperativo, un par de ellos no lo están. 
Tiene solución, hay forma de cambiar los mensajes de los commits, pero por ahora no te líes, implica hacer Squash y lo dejamos para otra ocasión :)

2022-02-05 09:16 UTC, isfegu commented on pages/index.tsx
>  import Image from 'next/image'
Aquí importas Image pero luego no lo usas ya que en la línea 24 usas el <img> de HTML en vez del <Image> de Next.js: https://nextjs.org/docs/basic-features/image-optimization

2022-02-05 09:16 UTC, isfegu commented on pages/index.tsx
> +import logo from './anonymath.svg';
Según veo en la documentación de Next.js, https://nextjs.org/docs/basic-features/image-optimization, no es necesario este import, usando el elemento <Image> se le puede especificar la URI de la imagen.

2022-02-05 09:16 UTC, isfegu commented on pages/index.tsx
> +import logo from './anonymath.svg';
Hemos de mirar si es posible ubicar los recursos gráficos en otro directorio que no sea pages, diría que el public puede ser un buen lugar. A ver qué dice Next.js.

2022-02-05 10:14 UTC, qbreis reviewed
Creo que ya puedo subir los cambios, este commit es de test, se puede eliminar, no se como :-S

2022-02-05 10:22 UTC, qbreis commented on pages/index.tsx
>  import Image from 'next/image'
En la línea 24 si que lo estoy usando para acceder al src {logo.src} pero no se si es mejor especificar la URI de la imagen como propones en el siguiente paso, en cuyo caso entonces ya podemos prescindir de este import.

2022-02-05 10:46 UTC, isfegu commented
> Efectivamente ya puedes subir cambios. No te preocupes, ya jugaremos a eliminar commits en otro momento.

2022-02-06 16:35 UTC, qbreis reviewed
Todavía me cuestan los conventional commits :-S Esto es referente a la carga imagen logotipo svg

2022-02-06 19:20 UTC, isfegu requested changes

2022-02-06 19:20 UTC, isfegu commented on pages/index.tsx
> +import logo2 from '../public/logo.svg';
¿Por qué le llamas al import logo2 y no simplemente logo?

2022-02-06 19:20 UTC, isfegu commented on pages/index.tsx
>            <a href="#">
Mira de usar el componente de Next.js Link, igual que el Image, por aquello de aprender más de Next.js. Lo pienso sobre todo por aquello de ver cómo combinar un enlace con una imagen dentro, situación que ya me he encontrado en sistemas de plantillas html y es interesante ver cómo lo resuelven en Next.js

2022-02-06 19:25 UTC, isfegu commented
> 

Bueno, los Conventional Commits es irles pillando el truco. Si un commit ves que has de poner la explicación de 3 cosas usando un +, es que algo se puede mejorar. Es posible que un único mensaje que englobe conceptualmente las 3 cosas sea la solución, pero a veces lo que denota es que has hecho un commit de cosas dispares que deberían haber sido 3 commits separados.
En este último commit, es más el primer caso. Se me ocurre algo así:
**refactor: Usa elemento Image para mostrar el logo**

2022-02-09 11:12 UTC, qbreis commented
Cuando me ponga voy a ver estos puntos que me comentas:

- style: Cambiar nombre de import logo2 por logo
- refactor: combinar Link e Image para logotipo

A parte de esto me gustaria seguir con el slider y he hecho esto en mi repositorio, le puedes echar una ojeada a ver que te parece: [https://github.com/qbreis/nextjs-carousel](https://github.com/qbreis/nextjs-carousel)

2022-02-12 09:13 UTC, qbreis reviewed
refactor: combinar Link para descargar PDF + build: añado archivo de … 
Tenía que haber hecho dos commits de esto:
refactor: CAMBIAR (NO COMBINAR) Link para descargar PDF
build: AÑADIR (NO AÑADO) archivo de descarga pdf a directorio public

2022-02-12 18:40 UTC, isfegu approved these changes

2022-02-13 09:15 UTC, merged